name: surav
description: "Quick Dio Request"
version: 1.0.1+1
homepage: https://github.com/codexsourav/surav
repository: https://github.com/codexsourav/surav
issue_tracker: https://github.com/codexsourav/surav/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

